version: '2.3'

networks:
  citrixhoneypot_local:

services:

# CitrixHoneypot service
  citrixhoneypot:
    build: .
    container_name: citrixhoneypot
    restart: always
    networks:
     - citrixhoneypot_local
    ports:
     - "443:443"
    image: "bboerst/citrixhoneypot:latest"
    read_only: true
    volumes:
     - /data/citrixhoneypot/logs:/opt/citrixhoneypot/logs
